GET http://localhost:3000/test
###

POST localhost:3000/test
Content-Type: application/json

{
  "example": "Here is an example"
}
###

GET localhost:3000/users
###

GET localhost:3000/users/2
###

DELETE localhost:3000/users/1