### // fetch all the users
GET http://localhost:3000/users

### // fetch a specif user
GET http://localhost:3000/users/2

### // create a user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Joe",
  "age": 55,
  "role": "ADMIN"
}

### // update a user
PATCH http://localhost:3000/users/3
Content-Type: application/json

{
  "age": 80
}

### // delete a user
DELETE http://localhost:3000/users/2