###
GET localhost:3000/users

###
GET localhost:3000/users/1

###
POST localhost:3000/users
Content-Type: application/json

{
  "name": "Carl",
  "age": 55,
  "role": "ADMIN"
}

###
PATCH localhost:3000/users/3
Content-Type: application/json

{
  "age": 80
}

###
DELETE localhost:3000/users/2